version: 0.2
 
phases:
  install:
    commands:
      - echo installing nginx...
      - sudo apt update
      - sudo apt install nginx -y
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html
    post_build:
      commands:
        - echo configuring nginx
artifacts:
  files:
    - '**/*'